#!/usr/bin/env python3
"""Compile plugin networking imports from the real packaged SDK (#580).

The optional argument names a built Horos.framework. Its binary is copied as a
read-only input; headers are regenerated by the real API-Headers.pl. No checkout
source paths are passed to clang. No app, Keychain access or network call runs.
"""
from pathlib import Path
import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ALIASES = ('HorosAPI', 'OsiriXAPI', 'OsiriX Headers', 'HorosDCM')
HEADERS = ('PluginFilter', 'DCMTKStoreSCU', 'DICOMTLS', 'DDKeychain')


def run(command, *, cwd, env=None):
    result = subprocess.run(command, cwd=cwd, env=env, capture_output=True,
                            text=True, timeout=60)
    assert result.returncode == 0, f'{command}:\n{result.stdout}\n{result.stderr}'
    return result.stdout


def check(source_framework, packager):
    with tempfile.TemporaryDirectory(prefix='horos network sdk ') as temporary:
        directory = Path(temporary)
        frameworks = directory / 'Frameworks'
        frameworks.mkdir()
        framework = frameworks / 'Horos.framework'
        shutil.copytree(source_framework, framework, symlinks=True)
        headers = framework / 'Versions/A/Headers'
        # An old build must not supply the header whose packaging we are testing.
        shutil.rmtree(headers)
        headers.mkdir()
        signature = framework / 'Versions/A/_CodeSignature'
        if signature.exists():
            shutil.rmtree(signature)
        environment = dict(os.environ, PROJECT_DIR=str(ROOT),
                           TARGET_BUILD_DIR=str(directory),
                           FULL_PRODUCT_NAME='Frameworks/Horos.framework',
                           PUBLIC_HEADERS_FOLDER_PATH='Frameworks/Horos.framework/Versions/A/Headers',
                           FRAMEWORKS_FOLDER_PATH='Frameworks', CODE_SIGNING_ALLOWED='NO')
        run(['perl', str(packager)], cwd=directory, env=environment)
        exported = headers / 'DDKeychain.h'
        assert exported.is_file(), 'SDK omits DDKeychain.h required by its DICOM networking headers'
        assert exported.read_bytes() == (ROOT / 'cocoahttpserver/DDKeychain.h').read_bytes()
        assert '#include <Horos/DDKeychain.h>' in (headers / 'Horos.h').read_text()
        assert (framework / 'Headers').resolve() == headers

        # CWD is outside the checkout and -F is the only include search option.
        compiler = ['xcrun', 'clang', '-F', str(frameworks)]
        for language in ('objective-c', 'objective-c++'):
            for header in HEADERS:
                source = directory / f'{header}.m'
                source.write_text(f'#import <Horos/{header}.h>\n')
                run(compiler + ['-x', language, '-fsyntax-only', str(source)], cwd=directory)
        print('ok: four independent SDK imports compile as Objective-C and Objective-C++')

        # Exercise the actual failure, not merely presence of a copied file.
        keychain_bytes = exported.read_bytes()
        exported.unlink()
        try:
            for header in ('DCMTKStoreSCU', 'DICOMTLS'):
                source = directory / f'{header}.m'
                missing = subprocess.run(compiler + ['-fsyntax-only', str(source)],
                                         cwd=directory, capture_output=True, text=True, timeout=60)
                assert missing.returncode != 0 and "'DDKeychain.h' file not found" in missing.stderr, \
                    f'{header} did not reproduce the missing transitive dependency: {missing.stderr}'
        finally:
            exported.write_bytes(keychain_bytes)
        print('ok: removing DDKeychain.h reproduces both original compiler failures')

        # These are normal host-resolved plugin symbols. The API framework is the
        # existing version-symbol library, not an implementation of the host.
        source = directory / 'NetworkPlugin.m'
        source.write_text('''#import <Horos/PluginFilter.h>
#import <Horos/DCMTKStoreSCU.h>
#import <Horos/DICOMTLS.h>
extern double HorosAPIVersionNumber;
_Static_assert(RequirePeerCertificate == 0 && VerifyPeerCertificate == 1 &&
               IgnorePeerCertificate == 2, "preserve public TLS verification values");
@interface NetworkPlugin : PluginFilter
@end
@implementation NetworkPlugin
- (long)filterImage:(NSString *)menuName {
    (void)[DCMTKStoreSCU sendSyntaxForListenerSyntax:0];
    (void)[DICOMTLS defaultCipherSuites];
    (void)[DDKeychain class];
    return HorosAPIVersionNumber > 0 ? 0 : -1;
}
@end
''')
        objects = []
        for language in ('objective-c', 'objective-c++'):
            obj = directory / f'{language}.o'
            run(compiler + ['-x', language, '-c', str(source), '-o', str(obj)], cwd=directory)
            objects.append(obj)
        run(['/bin/sh', str(ROOT / 'Horos/Scripts/Horos/API.sh')],
            cwd=directory, env=environment)
        for name in ('Horos', *ALIASES):
            for obj in objects:
                bundle = directory / f'{name}-{obj.stem}.bundle'
                run(['xcrun', 'clang++', '-bundle', '-undefined', 'dynamic_lookup',
                     '-F', str(frameworks), '-framework', name, '-framework', 'Cocoa',
                     str(obj), '-o', str(bundle)], cwd=directory)
                libraries = run(['xcrun', 'otool', '-L', str(bundle)], cwd=directory)
                assert 'Horos.framework/Versions/A/Horos' in libraries, libraries
                symbols = run(['xcrun', 'nm', '-m', '-u', str(bundle)], cwd=directory)
                assert '_HorosAPIVersionNumber (from Horos)' in symbols, symbols
                for class_name in ('PluginFilter', 'DCMTKStoreSCU', 'DICOMTLS', 'DDKeychain'):
                    assert f'_OBJC_CLASS_$_{class_name} (dynamically looked up)' in symbols, symbols
            if name != 'Horos':
                assert not (frameworks / f'{name}.framework/Headers').exists()
                assert (frameworks / f'{name}.framework/Versions/A/{name}').is_file()
        print('ok: native plugin links through Horos and all four existing framework aliases')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('framework', nargs='?', type=Path,
                        default=ROOT / 'build/Build/Products/Debug/Horos.framework')
    parser.add_argument('--packager', type=Path,
                        default=ROOT / 'Horos/Scripts/Horos/API-Headers.pl',
                        help='override to reproduce an earlier packaging revision')
    arguments = parser.parse_args()
    if not (arguments.framework / 'Versions/A/Horos').is_file():
        print('skipped: needs built Horos.framework; pass its path as the first argument', file=sys.stderr)
        return 2
    check(arguments.framework.resolve(), arguments.packager.resolve())
    return 0


if __name__ == '__main__':
    sys.exit(main())
