#!/usr/bin/env python3
"""The planar Metal renderer draws opacity tables as the original does (#657).

Every PT series opens with an opacity table (`PETOpacityTable`, Logarithmic by
default), and the planar snapshot used to refuse any image with one, so the most
common PET study showed «Original renderer (Metal paused)». The table now runs
in Metal: `PlanarTransferPass` makes each source pixel's display byte with the
host's arithmetic, and the fragment interpolates those bytes before the CLUT,
as the original renderer does.

No app, no window. The reference is the original renderer's own code:

* the display bytes come from the loop of `applyNonLinearWLWWThread:` and the
  polarity loop of `compute8bitRepresentation`, extracted from DCMPix.m and
  compiled, with the host's `vImageScale_Planar8` enlargement and flags;
* the tables come from `tableWith4096Entries:` (OpacityTransferView.m) fed with
  the menu's own points, generated by the OPACITY block of DefaultsOsiriX.m;
* the picture comes from the OpenGL scalar CLUT program the original renderer
  draws those bytes with (`LegacyScalarCLUT.swift`, level 0.5, width 1).

Tolerance, fixed before comparing: at texel centres the Metal image equals the
host bytes through the CLUT, byte for byte, for Logarithmic, Logarithmic
Inverse and Smooth, three windows, both polarities, nearest and linear sampling
and the 2x/3x software enlargement. Linear Table is no table: its frames keep
the float path this change does not touch. Between texels both
renderers mix the same bytes in float: a pixel whose exact value comes within
eight float32 ULPs of its texture coordinate, propagated through the
interpolation (A111's plan-v2), plus eight of the value, of a rounding boundary
may take the adjacent entry; those cases are counted, anything else fails.

Also checked: RGB images take the table through the host's 256-entry conversion,
composed into the CLUT; the Metal 4 pilot draws the same bytes; malformed tables
are refused; every row of the host's threaded table loop is assigned to a thread;
the bridge no longer refuses the table and still refuses everything else.

`<git revision>` as an optional argument reads the sources from that revision,
the negative control.
"""
from pathlib import Path
import re
import subprocess
import sys
import tempfile

root = Path(__file__).resolve().parents[1]
revision = sys.argv[1] if len(sys.argv) > 1 else None


def read(path):
    if revision:
        return subprocess.check_output(['git', '-C', str(root), 'show', revision + ':' + path]).decode('latin1')
    return (root / path).read_bytes().decode('latin1')


failures = []
bridge = read('Horos/Sources/PlanarHostBridge.m')
renderer = read('Horos/Sources/PlanarMetalRenderer.swift')
pilot = read('Horos/Sources/PlanarMetal4Renderer.swift')
pix = read('Horos/Sources/DCMPix.m')

# --- the bridge: the table is passed, everything else is still refused ------
snapshot = bridge[bridge.index('- (NSDictionary *)horosPlanarSnapshot'):]
refusal = snapshot[:snapshot.index('return @{@"error": unsupported};')]
if 'transferFunctionPtr' in refusal:
    failures.append('the planar snapshot still refuses an image with an opacity table')
# The modes the Metal path does not draw yet stay refused. The thick slab moved
# to #659, the convolution filter to #661, subtraction and the shutter to #662,
# fusion to #658, channel factors and colour enlargement to #660, each with its
# own test.
for kept in ['pix.thickSlabVRActivated', 'pix.stackMode', 'pix.isLUT12Bit']:
    if kept not in refusal:
        failures.append('the snapshot no longer refuses %s, which the Metal path does not draw yet' % kept)
if 'width > 16384 || height > 16384 || count > 512*1024*1024' not in snapshot:
    failures.append('the snapshot lost its size ceiling')
for key, value in [('transferFunction', 'pix.transferFunction'), ('transferLevel', 'noScale ? 127 : pix.wl'),
                   ('transferWidth', 'noScale ? 256 : pix.ww'), ('transferInverted', 'pix.displayInverted')]:
    if 'snapshot[@"%s"] = @(%s)' % (key, value) not in snapshot and 'snapshot[@"%s"] = %s' % (key, value) not in snapshot:
        failures.append('the snapshot does not pass %s as %s, which is what the host reads' % (key, value))

# --- one upload for both backends --------------------------------------------
update = pilot[pilot.index('func update(_ next: PlanarFrame)'):pilot.index('func clear()')]
textures = renderer[renderer.index('struct PlanarTextures'):renderer.index('final class PlanarMetalRenderer')]
if 'PlanarTextures(next, reusing: textures, device: device)' not in update or \
        textures.count('try PlanarMetalRenderer.makeTextures(for:') != 2:
    failures.append('the Metal 4 pilot prepares its own textures instead of the shared upload')
for forbidden in ['metal_stdlib', 'kernel void', 'transferFunction']:
    if forbidden in pilot:
        failures.append('the pilot carries its own table arithmetic (%s)' % forbidden)

# --- every row of the host's table loop has a thread -------------------------
partition = re.search(r'start = ([^;]*);\s*end = ([^;]*);', pix[pix.index('nonLinearWLWWThreads addObject'):])
if not partition:
    failures.append('the threaded table loop has no recognisable row partition')
else:
    def rows(expression, i, height, threads):
        python = expression.replace('(int)', '').replace('numberOfThreadsForCompute', str(threads))
        python = python.replace('height', str(height)).replace('i', str(i)).replace('/', '//')
        return eval(python)
    uncovered = []
    for threads in range(1, 13):
        for height in range(1, 1025):
            covered = []
            for i in range(threads):
                covered += range(rows(partition.group(1), i, height, threads), rows(partition.group(2), i, height, threads))
            if sorted(covered) != list(range(height)):
                uncovered.append((height, threads, height - len(set(covered))))
    if uncovered:
        height, threads, missing = next(u for u in uncovered if u[0] == 128 and u[1] == 10) \
            if any(u[0] == 128 and u[1] == 10 for u in uncovered) else uncovered[0]
        failures.append('the threaded table loop leaves rows unassigned in %d of 12288 cases, '
                        'e.g. %d of %d rows on %d threads' % (len(uncovered), missing, height, threads))

if 'struct PlanarTransfer' not in renderer or 'PlanarTransferPass' not in renderer:
    failures.append('the planar renderer has no opacity-table stage')
    for failure in failures:
        print('FAIL:', failure)
    raise SystemExit(1)

# --- the host's code, compiled -----------------------------------------------
thread = pix[pix.index('- (void)applyNonLinearWLWWThread:'):]
thread = thread[:thread.index('@end')]
host_from = re.search(r'float\s+from = \[o wl\] - \[o ww\]/2\.;', thread).group()
host_ratio = re.search(r'float\s+ratio = 4096\. / \[o ww\];', thread).group()
host_loop = re.search(r'while\( ii-- > 0\)\s*\{[^{}]*\}', thread).group()
invert = re.search(r'for\( NSUInteger i = 0; i < \(NSUInteger\) width \* height; \+\+i\)\s*'
                   r'\(\(unsigned char\*\) baseAddr\)\[i\] = 255 - \(\(unsigned char\*\) baseAddr\)\[i\];', pix).group()
rgb = pix[pix.index('// ***** SOURCE IMAGE IS RGBA'):]
rgb_loops = re.findall(r'for\( long i = 0; i < 256; i\+\+\)\s*\{[^{}]*convTable\[i\] = val;\s*\}', rgb)
rgb_table_loop = next(loop for loop in rgb_loops if 'transferFunctionPtr' in loop)
rgb_span = re.search(r'long\s+diff = max - min, val;', rgb).group()
rgb_zero = re.search(r'if\( diff == 0\) diff = 1;', rgb)
bounds = re.search(r'min = iwl - iww / 2;\s*max = iwl \+ iww / 2;', pix).group()
opacity = read('Horos/Sources/OpacityTransferView.m')
table_body = re.search(r'\+ \(NSData\*\) tableWith4096Entries: \(NSArray\*\) pointsArray\s*(\{.*?\n\})', opacity, re.S).group(1)
defaults = read('Horos/Sources/DefaultsOsiriX.m')
presets = defaults[defaults.index('// ** OPACITY TABLES'):defaults.index('[defaultValues setObject:opacityValues forKey:@"OPACITY"];')]
quality = re.search(r'^#define QUALITY (\w+)$', read('Horos/Sources/DCMView.m'), re.M).group(1)

host = '''#import <Foundation/Foundation.h>
#import <Accelerate/Accelerate.h>
#include <math.h>
#import "Host.h"
NSDictionary *hostOpacityPresets(void) {
    int i;
    NSMutableDictionary *defaultValues = [NSMutableDictionary dictionary];
''' + presets + '''
    [defaultValues setObject:opacityValues forKey:@"OPACITY"];
    return [defaultValues objectForKey:@"OPACITY"];
}
NSData *hostTable4096(NSArray *pointsArray) ''' + table_body + '''
void hostTransfer(float *src32Ptr, unsigned char *dst8Ptr, int ii, float hostWL, float hostWW, float *tfPtr) {
    ''' + host_from.replace('[o wl]', 'hostWL').replace('[o ww]', 'hostWW') + '''
    ''' + host_ratio.replace('[o ww]', 'hostWW') + '''
    ''' + host_loop + '''
}
void hostInvert(unsigned char *baseAddr, long width, long height) {
    ''' + invert + '''
}
void hostRGBTransferTable(float iwl, float iww, float *transferFunctionPtr, unsigned char *convTable) {
    float min, max;
    ''' + bounds + '''
    ''' + rgb_span + '''
    ''' + (rgb_zero.group() if rgb_zero else '') + '''
    ''' + rgb_table_loop + '''
}
long hostScale8(unsigned char *source, unsigned char *output, int width, int height, int scale) {
    vImage_Buffer src = {source, height, width, width};
    vImage_Buffer dst = {output, height * scale, width * scale, width * scale};
    return vImageScale_Planar8(&src, &dst, NULL, ''' + quality + ''');
}
'''
header = '''#import <Foundation/Foundation.h>
NSDictionary *hostOpacityPresets(void);
NSData *hostTable4096(NSArray *pointsArray);
void hostTransfer(float *src32Ptr, unsigned char *dst8Ptr, int ii, float hostWL, float hostWW, float *tfPtr);
void hostInvert(unsigned char *baseAddr, long width, long height);
void hostRGBTransferTable(float iwl, float iww, float *transferFunctionPtr, unsigned char *convTable);
long hostScale8(unsigned char *source, unsigned char *output, int width, int height, int scale);
'''

DRIVER = r'''
import AppKit
import Metal
import OpenGL.GL

func expect(_ ok: Bool, _ reason: @autoclosure () -> String) { if !ok { print("FAIL: " + reason()); exit(1) } }

@main @MainActor struct Check {
    static func main() throws {
        guard let device = MTLCreateSystemDefaultDevice() else { print("skipped: no Metal device"); exit(2) }
        let attributes: [NSOpenGLPixelFormatAttribute] = [UInt32(NSOpenGLPFAAccelerated),
            UInt32(NSOpenGLPFAColorSize), 24, UInt32(NSOpenGLPFAAllowOfflineRenderers), 0]
        guard let format = NSOpenGLPixelFormat(attributes: attributes),
              let context = NSOpenGLContext(format: format, share: nil) else { print("skipped: no OpenGL"); exit(2) }
        context.makeCurrentContext()
        let metal = try PlanarMetalRenderer(device: device)
        let pilot = PlanarMetal4Renderer.isSupported(device) ? try PlanarMetal4Renderer(device: device) : nil
        let state = LegacyScalarCLUTState()

        // The menu's tables, built by the host from the menu's own points.
        let presets = hostOpacityPresets()! as NSDictionary
        var tables: [(String, Data?)] = [("Linear Table", nil)]
        for name in ["Logarithmic Table", "Logarithmic Inverse Table", "Smooth Table"] {
            let preset = presets[name] as! NSDictionary
            tables.append((name, hostTable4096(preset["Points"] as! [Any])!))
        }
        expect(tables.count == 4, "the menu's tables were not all built")

        // A PET-like source with odd dimensions: calibrated values across and
        // beyond each window, fractions, values on table-index boundaries, and
        // the non-finite values the host's integer conversion clamps.
        let w = 29, h = 19
        var source = (0..<w * h).map { i -> Float in Float((i * 7919) % 21000) * 0.97 - 350 + Float(i % 7) * 0.125 }
        source[5] = .nan; source[6] = .infinity; source[7] = -.infinity; source[8] = 3.0e38
        let windows: [(Float, Float)] = [(4000, 8000), (1250.5, 2401.25), (127, 256)]
        for (level, width) in windows {
            // Exactly on index boundaries of this window: ratio*(v-from) integral.
            let from = Float(Double(level) - Double(width) / 2), ratio = Float(4096 / Double(width))
            for k in 0..<40 { source[40 + k] = from + Float(k * 101) / ratio }
        }
        let floats = source.withUnsafeBytes { Data($0) }
        var discrete = [UInt8](), gray = [UInt8]()
        for i in 0..<256 {
            discrete += [UInt8(i), UInt8(255 - i), UInt8((i * 73) % 256), 255]
            gray += [UInt8(i), UInt8(i), UInt8(i), 255]
        }

        func hostBytes(_ table: Data, _ level: Float, _ width: Float, _ inverted: Bool) -> [UInt8] {
            var bytes = [UInt8](repeating: 0, count: w * h)
            var values = table.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
            hostTransfer(&source, &bytes, Int32(w * h), level, width, &values)
            if inverted { hostInvert(&bytes, w, h) }
            return bytes
        }
        func enlarge(_ bytes: [UInt8], _ scale: Int) -> [UInt8] {
            guard scale > 1 else { return bytes }
            var copy = bytes, enlarged = [UInt8](repeating: 0, count: w * h * scale * scale)
            expect(hostScale8(&copy, &enlarged, Int32(w), Int32(h), Int32(scale)) == 0, "vImage failed")
            return enlarged
        }
        func snapshot(_ table: Data?, _ level: Float, _ width: Float, _ inverted: Bool, clut: [UInt8],
                      points: [Float], view: [Int], scale: Int, nearest: Bool) -> NSDictionary {
            let value: NSMutableDictionary = ["width": w, "height": h, "pixels": floats, "clut": Data(clut),
                "frameIdentity": "transfer", "level": level, "widthWindow": inverted ? -width : width,
                "screenToPixel": points, "viewSize": view, "softwareScale": scale, "nearest": nearest]
            if let table {
                value["transferFunction"] = table; value["transferLevel"] = level
                value["transferWidth"] = width; value["transferInverted"] = inverted
            }
            return value
        }

        // 0. Linear is no table: the frame keeps the float path, which windows
        //    in the fragment exactly as before this change.
        for (level, width) in windows {
            let frame = try PlanarFrame(snapshot(nil, level, width, false, clut: discrete,
                points: [0, 0, Float(w), 0, 0, Float(h)], view: [w, h], scale: 1, nearest: true))
            expect(frame.transfer == nil && frame.window == SIMD4(level, width, 0, 1),
                   "Linear Table no longer draws through the unchanged float path")
        }

        // 1. Texel centres: Metal equals the host's bytes through the CLUT.
        var exact = 0
        for (name, table) in tables.dropFirst() { for (level, width) in windows { for inverted in [false, true] {
            let host = hostBytes(table!, level, width, inverted)
            for scale in [1, 2, 3] { for nearest in (scale == 1 ? [false, true] : [false]) { for clut in [discrete, gray] {
                let tw = w * scale, th = h * scale
                let enlarged = enlarge(host, scale)
                let frame = try PlanarFrame(snapshot(table, level, width, inverted, clut: clut,
                    points: [0, 0, Float(w), 0, 0, Float(h)], view: [tw, th], scale: scale, nearest: nearest))
                try metal.update(frame)
                let drawn = [UInt8](try metal.renderBGRA(width: tw, height: th))
                for i in 0..<tw * th {
                    let entry = Int(enlarged[i]) * 4
                    let expected = [clut[entry + 2], clut[entry + 1], clut[entry], 255]
                    expect(Array(drawn[i * 4..<i * 4 + 4]) == expected,
                           "\(name) level=\(level) width=\(width) inverted=\(inverted) scale=\(scale) nearest=\(nearest) texel=\(i % tw),\(i / tw): host byte \(enlarged[i]) drawn \(Array(drawn[i * 4..<i * 4 + 4]))")
                }
                exact += tw * th
                if let pilot {
                    try pilot.update(frame)
                    let piloted = try pilot.renderBGRA(width: tw, height: th)
                    expect(piloted == Data(drawn), "the Metal 4 pilot drew \(name) differently")
                }
            }}}
        }}}

        // 2. Between texels: Metal against the original's OpenGL program on the
        //    host bytes, through a discrete CLUT, oblique and letterboxed.
        let outW = 128, outH = 64
        var fbo: GLuint = 0, target: GLuint = 0, input: GLuint = 0
        glGenFramebuffersEXT(1, &fbo); glBindFramebufferEXT(GLenum(GL_FRAMEBUFFER_EXT), fbo)
        glGenTextures(1, &target); glBindTexture(GLenum(GL_TEXTURE_2D), target)
        glTexImage2D(GLenum(GL_TEXTURE_2D), 0, GL_RGBA8, GLsizei(outW), GLsizei(outH), 0,
                     GLenum(GL_BGRA), GLenum(GL_UNSIGNED_BYTE), nil)
        glFramebufferTexture2DEXT(GLenum(GL_FRAMEBUFFER_EXT), GLenum(GL_COLOR_ATTACHMENT0_EXT),
                                  GLenum(GL_TEXTURE_2D), target, 0)
        expect(glCheckFramebufferStatusEXT(GLenum(GL_FRAMEBUFFER_EXT)) == GLenum(GL_FRAMEBUFFER_COMPLETE_EXT),
               "no OpenGL framebuffer")
        glGenTextures(1, &input); glViewport(0, 0, GLsizei(outW), GLsizei(outH))
        glMatrixMode(GLenum(GL_PROJECTION)); glLoadIdentity()
        glMatrixMode(GLenum(GL_MODELVIEW)); glLoadIdentity()
        glDisable(GLenum(GL_BLEND)); glDisable(GLenum(GL_DEPTH_TEST))
        var compared = 0, boundary = 0, identical = 0
        for (name, table) in tables.dropFirst() { for (level, width) in windows.prefix(2) { for inverted in [false, true] {
            let host = hostBytes(table!, level, width, inverted)
            for scale in [1, 3] { for nearest in (scale == 1 ? [false, true] : [false]) {
                for points: [Float] in [[0, 0, Float(w), 0, 0, Float(h)], [1, 0.3, 23, 2.3, -0.5, 16.1]] {
                    let tw = w * scale, th = h * scale
                    let enlarged = enlarge(host, scale)
                    glActiveTexture(GLenum(GL_TEXTURE0))
                    glBindTexture(GLenum(GL_TEXTURE_RECTANGLE_EXT), input)
                    glPixelStorei(GLenum(GL_UNPACK_ALIGNMENT), 1); glPixelStorei(GLenum(GL_UNPACK_ROW_LENGTH), 0)
                    glTexImage2D(GLenum(GL_TEXTURE_RECTANGLE_EXT), 0, GL_INTENSITY8, GLsizei(tw), GLsizei(th), 0,
                                 GLenum(GL_LUMINANCE), GLenum(GL_UNSIGNED_BYTE), enlarged)
                    let filter = nearest ? GL_NEAREST : GL_LINEAR
                    for parameter in [GL_TEXTURE_MIN_FILTER, GL_TEXTURE_MAG_FILTER] {
                        glTexParameteri(GLenum(GL_TEXTURE_RECTANGLE_EXT), GLenum(parameter), filter)
                    }
                    for parameter in [GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T] {
                        glTexParameteri(GLenum(GL_TEXTURE_RECTANGLE_EXT), GLenum(parameter), GL_CLAMP_TO_EDGE)
                    }
                    // The original draws host-prepared bytes with level 0.5, width 1.
                    let draw = state.prepare(table: Data(discrete), level: 0.5, width: 1, nearest: nearest, context: context)!
                    glActiveTexture(GLenum(GL_TEXTURE1))
                    expect(draw.begin(), "the OpenGL scalar program did not start")
                    func vertex(_ x: Float, _ y: Float, _ px: Float, _ py: Float) {
                        glTexCoord2f(px * Float(scale), py * Float(scale)); glVertex2f(x, y)
                    }
                    glBegin(GLenum(GL_QUADS))
                    vertex(-1, 1, points[0], points[1]); vertex(1, 1, points[2], points[3])
                    vertex(1, -1, points[2] + points[4] - points[0], points[3] + points[5] - points[1])
                    vertex(-1, -1, points[4], points[5]); glEnd()
                    draw.end()
                    var gl = [UInt8](repeating: 0, count: outW * outH * 4)
                    glPixelStorei(GLenum(GL_PACK_ALIGNMENT), 1)
                    glReadPixels(0, 0, GLsizei(outW), GLsizei(outH), GLenum(GL_BGRA), GLenum(GL_UNSIGNED_BYTE), &gl)
                    let frame = try PlanarFrame(snapshot(table, level, width, inverted, clut: discrete,
                        points: points, view: [outW, outH], scale: scale, nearest: nearest))
                    try metal.update(frame)
                    let drawn = [UInt8](try metal.renderBGRA(width: outW, height: outH))
                    func byte(_ x: Int, _ y: Int) -> Double {
                        Double(enlarged[min(th - 1, max(0, y)) * tw + min(tw - 1, max(0, x))]) / 255
                    }
                    for y in 0..<outH { for x in 0..<outW {
                        let u = (Double(x) + 0.5) / Double(outW), v = (Double(y) + 0.5) / Double(outH)
                        let px = (Double(points[0]) + u * Double(points[2] - points[0]) + v * Double(points[4] - points[0])) * Double(scale)
                        let py = (Double(points[1]) + u * Double(points[3] - points[1]) + v * Double(points[5] - points[1])) * Double(scale)
                        let original = Array(gl[((outH - 1 - y) * outW + x) * 4..<((outH - 1 - y) * outW + x) * 4 + 4])
                        let ported = Array(drawn[(y * outW + x) * 4..<(y * outW + x) * 4 + 4])
                        compared += 1
                        // Outside the image GL clamps to the edge texel and Metal
                        // clears; a thousandth of a texel keeps float noise out.
                        if px < 0.001 || py < 0.001 || px > Double(tw) - 0.001 || py > Double(th) - 0.001 { continue }
                        if original == ported { identical += 1; continue }
                        func sample(_ px: Double, _ py: Double) -> Double {
                            if nearest { return byte(Int(floor(px)), Int(floor(py))) }
                            let xx = px - 0.5, yy = py - 0.5, ix = Int(floor(xx)), iy = Int(floor(yy))
                            let dx = xx - Double(ix), dy = yy - Double(iy)
                            return byte(ix, iy) * (1 - dx) * (1 - dy) + byte(ix + 1, iy) * dx * (1 - dy)
                                + byte(ix, iy + 1) * (1 - dx) * dy + byte(ix + 1, iy + 1) * dx * dy
                        }
                        // Both renderers carry the texture coordinate in float:
                        // eight float32 ULPs of it, propagated through the
                        // interpolation, plus eight of the interpolated value.
                        let reach = Double(Float(max(abs(px), abs(py)) + 1).ulp) * 8
                        var low = Double.infinity, high = -Double.infinity
                        for ox in [-reach, 0, reach] { for oy in [-reach, 0, reach] {
                            let v = sample(px + ox, py + oy); low = min(low, v); high = max(high, v)
                        }}
                        let value = sample(px, py)
                        let slack = Double(Float(high).ulp) * 8
                        func entry(_ scalar: Double) -> Int { Int(floor(min(1, max(0, scalar)) * 255 + 0.5)) }
                        let allowed = (entry(low - slack)...entry(high + slack)).map { i -> [UInt8] in
                            [discrete[i * 4 + 2], discrete[i * 4 + 1], discrete[i * 4], 255]
                        }
                        expect(allowed.contains(original) && allowed.contains(ported),
                               "\(name) level=\(level) inverted=\(inverted) scale=\(scale) nearest=\(nearest) pixel=\(x),\(y): original \(original) Metal \(ported) value \(value * 255)")
                        boundary += 1
                    }}
                }
            }}
        }}}
        expect(glGetError() == GLenum(GL_NO_ERROR), "OpenGL error")
        expect(identical > compared / 2, "too few pixels compared inside the image (\(identical) of \(compared))")

        // 3. RGB takes the table in its 256-entry conversion, composed into the CLUT.
        var argb = [UInt8]()
        for i in 0..<w * h { argb += [255, UInt8((i * 31) % 256), UInt8((i * 97 + 13) % 256), UInt8(i % 256)] }
        var rgbChecked = 0
        for (name, table) in tables.dropFirst() { for (level, width) in [(Float(127), Float(256)), (100, 180.5)] {
            var values = table!.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
            var conversion = [UInt8](repeating: 0, count: 256)
            hostRGBTransferTable(level, width, &values, &conversion)
            let value: NSMutableDictionary = ["width": w, "height": h, "pixels": Data(argb), "clut": Data(discrete),
                "frameIdentity": "rgb-transfer", "level": level, "widthWindow": width, "isColor": true, "nearest": true,
                "screenToPixel": [0.0, 0.0, Double(w), 0.0, 0.0, Double(h)], "viewSize": [w, h],
                "transferFunction": table!, "transferLevel": level, "transferWidth": width, "transferInverted": false]
            let frame = try PlanarFrame(value)
            expect(frame.transfer == nil, "an RGB frame kept a scalar table stage")
            try metal.update(frame)
            let drawn = [UInt8](try metal.renderBGRA(width: w, height: h))
            for i in 0..<w * h {
                let expected = [discrete[Int(conversion[Int(argb[i * 4 + 3])]) * 4 + 2],
                                discrete[Int(conversion[Int(argb[i * 4 + 2])]) * 4 + 1],
                                discrete[Int(conversion[Int(argb[i * 4 + 1])]) * 4], UInt8(255)]
                expect(Array(drawn[i * 4..<i * 4 + 4]) == expected, "RGB \(name) level=\(level) pixel \(i)")
            }
            rgbChecked += w * h
        }}

        // 4. Malformed tables are refused, never drawn some other way.
        for (key, bad) in [("transferFunction", Data(count: 4095 * 4)), ("transferWidth", 0.0), ("transferLevel", Double.nan)] as [(String, Any)] {
            let value = snapshot(tables[1].1, 100, 200, false, clut: discrete, points: [0, 0, Float(w), 0, 0, Float(h)],
                                 view: [w, h], scale: 1, nearest: true).mutableCopy() as! NSMutableDictionary
            value[key] = bad
            do { _ = try PlanarFrame(value); expect(false, "accepted a malformed \(key)") } catch {}
        }
        expect(source.withUnsafeBytes { Data($0) } == floats, "the source samples changed")
        print("PASS: \(exact) texel-centre pixels exact (3 tables, Linear unchanged, 3 windows, both polarities, 1x/2x/3x\(pilot == nil ? "" : ", Metal 4 pilot identical")); \(compared) pixels against the original OpenGL program, \(boundary) float32 boundary cases; \(rgbChecked) RGB pixels exact")
    }
}
'''

with tempfile.TemporaryDirectory(prefix='horos-planar-transfer-') as directory:
    work = Path(directory)
    sources = {}
    for name in ['VolumeAllocation.swift', 'PlanarMetalRenderer.swift', 'PlanarMetal4Renderer.swift',
                 'MetalPerformanceTrace.swift', 'LegacyScalarCLUT.swift', 'VolumeSession.swift',
                 'MPRMetalReslicer.swift', 'MetalComputePipelineCache.swift', 'Metal4ComputeSubmitter.swift']:
        sources[name] = work / name
        sources[name].write_text(read('Horos/Sources/' + name))
    (work / 'Host.h').write_text(header)
    (work / 'Host.m').write_text(host)
    (work / 'Check.swift').write_text(DRIVER)
    subprocess.run(['xcrun', 'clang', '-O2', '-fno-objc-arc', '-c', str(work / 'Host.m'), '-o', str(work / 'Host.o')],
                   check=True)
    build = subprocess.run(['xcrun', 'swiftc', '-O', '-parse-as-library', '-suppress-warnings',
                            *[str(path) for path in sources.values()], str(work / 'Host.o'),
                            '-import-objc-header', str(work / 'Host.h'), '-framework', 'Accelerate',
                            str(work / 'Check.swift'), '-o', str(work / 'check')])
    if build.returncode != 0:
        failures.append('the renderer does not build with the opacity-table driver')
    else:
        result = subprocess.run([str(work / 'check')], timeout=120)
        if result.returncode == 2 and not failures:
            raise SystemExit(2)
        if result.returncode != 0:
            failures.append('the Metal drawing differs from the original renderer (see above)')

if failures:
    for failure in failures:
        print('FAIL:', failure)
    raise SystemExit(1)
