#!/usr/bin/env python3
"""Every superclass in the generated Swift header must be declared by the prefix
header.

`Horos-Swift.h` re-declares each `@objc` Swift class for Objective-C, including
its superclass, and the framework imports it writes for those superclasses sit
behind `#if __has_feature(objc_modules)`. This target compiles without modules,
so those imports vanish and the superclass has to come from somewhere else. When
it does not, every file that includes the generated header stops compiling:

    Horos-Swift.h:2418:36: error: cannot find interface declaration for
    'NSPreferencePane', superclass of 'HorosMenuShortcutPref'

This check compiles one probe against nothing but the prefix header, which is
the same question the build asks, without needing a full build.
"""
from pathlib import Path
import re
import subprocess
import sys
import tempfile

root = Path(__file__).resolve().parents[1]
prefix = root / 'Horos/prefix.pch'
failures = []

declaration = re.compile(
    r'@objc\((\w+)\)\s*(?:@\w+\s*)*(?:public\s+|internal\s+|final\s+|open\s+)*'
    r'class\s+(\w+)\s*:\s*(\w+)')

superclasses = {}
for source in sorted((root / 'Horos/Sources').glob('*.swift')):
    text = source.read_text(encoding='utf-8', errors='replace')
    for match in declaration.finditer(text):
        superclasses.setdefault(match.group(3), set()).add(source.name)

if not superclasses:
    print('FAIL: no @objc Swift class was found to check', file=sys.stderr)
    sys.exit(1)

# A superclass declared in the checkout comes from a project header, not from a
# framework, so the prefix header is not responsible for it.
project_classes = set()
for pattern in ('Horos/Sources/*.h', 'Horos/Sources/*.swift'):
    for source in root.glob(pattern):
        text = source.read_text(encoding='utf-8', errors='replace')
        # Only a real class declaration counts; `@interface NSPreferencePane
        # (Horos)` is a category on a framework class, not a definition of it.
        project_classes.update(re.findall(r'@interface\s+(\w+)\s*:', text))
        project_classes.update(re.findall(r'@objc\((\w+)\)', text))

external = sorted(name for name in superclasses if name not in project_classes)

sdk = subprocess.run(['xcrun', '--show-sdk-path'], capture_output=True, text=True)
if sdk.returncode != 0:
    print('needs an installed SDK: %s' % sdk.stderr.strip(), file=sys.stderr)
    raise SystemExit(2)

def resolves(names, tmp):
    """Compile one probe subclassing each name; return the names clang rejected."""
    if not names:
        return []
    probe = Path(tmp) / ('probe-%d.m' % abs(hash(tuple(names))))
    body = ['// Generated by tests/test-swift-header-superclasses.py']
    for index, name in enumerate(names):
        body.append('@interface HorosPrefixProbe%d : %s\n@end' % (index, name))
        body.append('@implementation HorosPrefixProbe%d\n@end' % index)
    probe.write_text('\n'.join(body) + '\n')
    done = subprocess.run(
        ['xcrun', 'clang', '-x', 'objective-c', '-fsyntax-only',
         '-isysroot', sdk.stdout.strip(),
         '-include', str(prefix), str(probe)],
        capture_output=True, text=True)
    if done.returncode == 0:
        return []
    rejected = []
    for line in done.stderr.splitlines():
        if 'error:' not in line:
            continue
        for name in names:
            if "'%s'" % name in line:
                rejected.append((name, line.split('error:')[-1].strip()))
                break
        else:
            rejected.append((None, line.strip()))
    return rejected


with tempfile.TemporaryDirectory(prefix='horos-swift-superclass-') as tmp:
    rejected = resolves(external, tmp)
    for name, message in rejected:
        if name is None:
            failures.append(message)
            continue
        # The Swift overlay renames some Foundation classes, and the generated
        # header emits the Objective-C name: Formatter is NSFormatter there.
        if not name.startswith('NS') and not resolves(['NS' + name], tmp):
            continue
        failures.append('%s is a superclass in %s but the prefix header does not '
                        'declare it: %s' % (name, ', '.join(sorted(superclasses[name])), message))

if failures:
    for item in failures:
        print('FAIL:', item, file=sys.stderr)
    sys.exit(1)
print('PASS: %d framework superclass(es) reachable from the prefix header: %s'
      % (len(external), ', '.join(external)))
